# Generated by Django 6.1 on 2026-09-08 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('read', 'Read only'), ('edit', 'Can edit')], default='read', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='workspace.storedfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workspace_fileshare',
                'constraints': [models.UniqueConstraint(fields=('file', 'user'), name='one_share_per_user_per_file')],
            },
        ),
    ]
